Environment: Dev
SourceType : Kafka
KafkaTopic: ["topic1-emp","topic1-dept"]
KafkaSchemaDataSetName: ["emp.avsc","dept.avsc"]
outputOptions:
  NoSqlDb: Cassandra
  DB: Mysql
  FileLoc: gs://shuva-buc
  BigqueryStageTable:
  SaveMode:
  targetTable: emp,dept
  mysqlDatabaseName: MyDB
  savemode: overwrite
FileConversion: CsvToText
explain: true
loglevels: Info
appName: GcpDataFlow
